name: Metrics
on:
  # Schedule daily updates
  schedule:
  - cron: '0 0 * * *'
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PROFILE_MATRIX_TOKEN }}
          
          # options
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_recent_days: 0
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_languages_limit: 0
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_archived: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_lines: yes
